# Generated by Django 5.0.7 on 2024-07-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Phone',
        ),
        migrations.AddField(
            model_name='student',
            name='Description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
