# Generated by Django 5.0.7 on 2024-07-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0002_remove_student_address_remove_student_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Status',
            new_name='status',
        ),
    ]
